catalog/urls.py
"""Определяем схему URL для приложения catalog"""

from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "catalog"

urlpatterns = [
    # Домашняя страница
    path("", views.index, name="index"),
    # path("books", views.books, name="books"),
    path("books/<int:page>", views.books, name="books"),
    path("book/<int:book_id>", views.book, name="book"),
    path("audio_books", views.audio_books, name="audio_books"),
    path("search_result", views.search_result, name="search_result"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

locallib/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("", include("catalog.urls")),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("regisrarion/", views.register, name="register"),
]

bot/models.py
from django.db import models


class TelegramUsers(models.Model):
    external_id = models.PositiveIntegerField(
        verbose_name="ID пользователя",
        unique=True,
    )
    first_name = models.CharField(
        max_length=100,
        verbose_name="Имя пользователя",
        null=True,
        blank=True,
    )
    last_name = models.CharField(
        max_length=100,
        verbose_name="Фамилия пользователя",
        null=True,
        blank=True,
    )

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

    class Meta:
        verbose_name = "Телеграм пользователь"
        verbose_name_plural = "Телеграм пользователи"

catalog/models.py
from django.db import models


class Author(models.Model):
    first_name = models.CharField(
        max_length=200,
        help_text="Введите имя автора",
        verbose_name="Имя",
    )
    last_name = models.CharField(
        max_length=200,
        help_text="Введите фамилию автора",
        verbose_name="Фамилия",
    )

    def save(self):
        self.first_name = self.first_name.lower()
        self.last_name = self.last_name.lower()
        return super(Author, self).save()

    def __str__(self):
        return "%s %s" % (self.first_name.capitalize(), self.last_name.capitalize())

    class Meta:
        verbose_name = "Автор"
        verbose_name_plural = "Авторы"


class Genre(models.Model):
    name = models.CharField(
        max_length=200,
        help_text="Введите наименование жанра",
        verbose_name="Жанр",
    )

    def save(self):
        self.name = self.name.lower()
        return super(Genre, self).save()

    def __str__(self):
        return self.name.capitalize()

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Book(models.Model):
    name = models.CharField(
        max_length=200,
        help_text="Введите название книги",
        verbose_name="Название",
    )
    author = models.ForeignKey(
        Author,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Автор",
    )
    genres = models.ManyToManyField(
        Genre,
        verbose_name="Жанр",
    )
    descript = models.TextField(
        help_text="Введите описаниние книги",
        verbose_name="Описание",
    )
    file = models.FileField(
        upload_to="files",
        verbose_name="Файл",
        null=True,
        blank=True,
    )
    cover = models.ImageField(
        upload_to="images",
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.name.capitalize()

    def save(self):
        self.name = self.name.lower()
        self.descript = self.descript.lower()
        return super(Book, self).save()

    class Meta:
        verbose_name = "Книга"
        verbose_name_plural = "Книги"

catalog/views.py
from django.shortcuts import render
from django.db.models import Q
from .models import Book
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET


@require_GET
def index(request):
    """Домашняя страница"""
    return render(request, "catalog/index.html")


@require_GET
def books(request, page):
    """выводит список книг"""
    # books_on_page можно вынети в настройки
    books_on_page = 4
    books_count = Book.objects.count()
    books = []
    prev_page = page - 1
    next_page = page + 1
    for book_id in range((page - 1) * books_on_page + 1, page * books_on_page + 1):
        if book_id <= books_count:
            books.append(Book.objects.get(id=book_id))
        if book_id + 1 > books_count:
            next_page = 0

    context = {
        "books": books,
        "next_page": next_page,
        "page": page,
        "prev_page": prev_page,
    }
    return render(request, "catalog/books.html", context)


@require_GET
def book(request, book_id):
    """Выводит информацию о книге"""
    book = Book.objects.get(id=book_id)
    context = {
        "name": book.name.capitalize(),
        "author": book.author,
        "genres": book.genres,
        "descript": book.descript.capitalize(),
        "file": book.file,
        "cover": book.cover,
    }
    return render(request, "catalog/book.html", context)


@require_GET
def audio_books(request):
    """Страница с аудиокнигами"""
    return render(request, "catalog/audio_books.html")


def search(query):
    """Поиск книги по названию и автору"""
    query_list = query.split(" ")
    if len(query_list) > 1:
        books_list = Book.objects.filter(
            Q(name__contains=query)
            | Q(author__first_name__contains=query_list[1])
            & Q(author__last_name__contains=query_list[0])
            | Q(author__first_name__contains=query_list[0])
            & Q(author__last_name__contains=query_list[1])
        )
    else:
        books_list = Book.objects.filter(
            Q(name__contains=query)
            | Q(author__first_name__contains=query)
            | Q(author__last_name__contains=query)
        )
    return books_list


@require_GET
def search_result(request):
    """страница результатов поиска"""
    context = {}
    query = request.GET.get("q").lower()
    books_list = search(query)
    if books_list:
        context["books_list"] = books_list
    context = {
        "books_list": books_list,
    }
    return render(request, "catalog/search_result.html", context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.http import require_http_methods


def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect(request.META.get("HTTP_REFERER"))
    context = {"form": form}
    return render(request, "registration/register.html", context)

catalog/templates/catalog/audio_books.html
{% extends "catalog/base.html" %}
{% block content%}
<p>Данный раздел находится в разработке</p>
{% endblock content%}

catalog/templates/catalog/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="rounded-start">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Электронная библиотека</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery="full" %}

</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'catalog:index'%}">
            Электронная библиотека</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'catalog:books' 1 %}">
                        Книги</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'catalog:audio_books'%}">
                        Аудиокниги</a>
                </li>
                <form class="d-flex" role="search" action="{% url 'catalog:search_result' %}" method="GET">
                    <input class="form-control me-2" name="q" type="search" placeholder="Книга или автор"
                        aria-label="Search">
                </form>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text" }">Привет, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>

        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>

</html>

catalog/templates/catalog/book.html
{% extends "catalog/base.html" %}
{% block content%}
<style>
    .leftimg {
        float: left;
        /* Выравнивание по левому краю */
        margin: 0 20px 20px 0;
        /* Отступы вокруг картинки */
    }
</style>
<div class="card mb-3">
    <h3 class="card-header">
        {{ name }}
    </h3>
    <div class="card-body">
        <p><img src="/media/{{ cover }}" class="leftimg" alt="connect" style="max-height:300px">
            О книге:
        <p>
            {{descript}}
        </p>
        </p>
        Автор: {{author}}
        <p>Жанр:
            {% for genre in genres.all %}
            {{ genre }}
            {% endfor %}
        </p>
        {% if user.is_authenticated %}
        <a href="/media/{{ file }}" class="btn btn-primary">epub</a>
        <a href="" class="btn btn-danger disabled">fb2</a>
        {% else %}
        <a href="{% url 'users:login' %}">Файлы для скачивания доступны только для авторизированных пользователей.</a>
        {% endif %}
    </div>
</div>
{% endblock content %}

catalog/templates/catalog/books.html
{% extends "catalog/base.html" %}
{% block content%}
<h2>Все книги</h2>
{% for book in books %}
<div class="card mb-3" style="max-width: 100%;">
    <div class="row g-0">
        <div class="col-md-2">
            <img src="/media/{{book.cover}}" class="img-fluid rounded-start" alt="Обложка не доступна" width="150">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{book}}</h5>
                <p class="card-text text-truncate" style="max-width: 800px;"> {{book.descript}}</p>
                <p class="card-text"><small class="text-muted">{{book.author}}</small></p>
                <a href="{% url 'catalog:book' book.id %}" class="btn btn-primary"> Подробнее</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<nav aria-label="Навигация по страницам">
    <ul class="pagination">
        {% if prev_page == 0 %} <li class="page-item disabled "><a class="page-link"
                href="{% url 'catalog:books' prev_page %}">Предыдущая</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="{% url 'catalog:books' prev_page %}">Предыдущая</a></li>
        {% endif %}
        <li class="page-item"><a class="page-link" href="{% url 'catalog:books' page %}">{{page}}</a></li>
        {% if next_page > 0 %}
        <li class="page-item"><a class="page-link" href="{% url 'catalog:books' next_page %}">Следующая</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="{% url 'catalog:books' next_page %}">Следующая</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endblock content%}

catalog/templates/catalog/index.html
{% extends "catalog/base.html" %}
{% block page_header %} <divclass='jumbotron'>
    <h1 class="display-5">Читай и слушай понравившиеся книги.</h1>
    </div>
    {% endblock page_header %}

catalog/templates/catalog/search_result.html
{% extends "catalog/base.html" %}
{% block content%}
<h2>Результат поиска</h2>
{% for book in books_list %}
<div class="card mb-3" style="max-width: 100%;">
    <div class="row g-0">
        <div class="col-md-2">
            <img src="/media/{{book.cover}}" class="img-fluid rounded-start" alt="Обложка не доступна" width="150">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{book.name}}</h5>
                <p class="card-text text-truncate" style="max-width: 800px;"> {{book.descript}}</p>
                <p class="card-text"><small class="text-muted">{{book.author}}</small></p>
                <a href="{% url 'catalog:book' book.id %}" class="btn btn-primary"> Подробнее</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock content%}